#!/bin/bash

g++ "$1"
g++ brute.cpp -o brute
g++ gen.cpp -o gen

for ((i = 1; i <= 1000; ++i)); do
    echo $i
    ./gen $i >int
    ./a.out <int >out1
    ./brute <int >out2
    diff -w out1 out2 || break
done